spatie/laravel-event-projector

composer.json

Laravel components doesn’t follow Semantic Versioning.
Good article about that: [https://medium.com/@vinkla/laravel-packages-and-semantic-versioning-f62dc5accee5](https://medium.com/@vinkla/laravel-packages-and-semantic-versioning-f62dc5accee5)

Fixes required version of illuminate components

---

database/migrations/create_stored_events_table.php.stub

This PR is a quick fix in `down()` method in the migration.

fixes down() method in migration

---

config/event-projector.php
src/Console/ReplayEventsCommand.php
src/EventProjectionist.php
src/EventSubscriber.php

Didn't go through everything, but went through the core. Looks great! Proposed a few changes here.
Regarding the `EventProjectionist` changes: Normally I'd consider injecting a `$replayChunkSize` variable instead of `$config` array, but if we'd ever want to add internal config we can now do it without changing `__construct`'s signature.

Review Seb

---

src/Console/Make/MakeProjectorCommand.php
src/Console/Make/MakeReactorCommand.php
src/Console/Make/MakeStorableEventCommand.php

Since the console commands has been moved to a directory deeper, the path to the stub was not right anymore.

Fix path to stub.

---

stubs/storable-event.stub

The use was missing in the stub

Added missing use on the storable-event stub

---

src/Console/Make/MakeProjectorCommand.php

`q` is already a shortcut for `--quiet`. Defining it here causes an error: 
```
[2018-06-26 15:09:15] local.ERROR: An option with shortcut "q" already exists. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\LogicException(code: 0): An option with shortcut \"q\" already exists. at D:\\projects\\test\\vendor\\symfony\\console\\Input\\InputDefinition.php:238)
[stacktrace]
#0 D:\\projects\\test\\vendor\\symfony\\console\\Input\\InputDefinition.php(222): Symfony\\Component\\Console\\Input\\InputDefinition->addOption(Object(Symfony\\Component\\Console\\Input\\InputOption))
#1 D:\\projects\\test\\vendor\\symfony\\console\\Command\\Command.php(298): Symfony\\Component\\Console\\Input\\InputDefinition->addOptions(Array)
#2 …
```

Changed 'queued' option shortcut

---

src/Projectionist.php

In addition to what was updated in [1.0.4](https://github.com/spatie/laravel-event-projector/releases/tag/1.0.4), this PR proposes to also use the `StoredEvent` model from the config in the `Projectionist` class.
Currently, when injecting a custom `StoredEvent` model in a projector, e.g. `App\Events\StoredEventWithMeta $storedEvent` and running the rebuild command, the following error shows up: `Argument 2 passed to (..) must be an instance of App\Events\StoredEventWithMeta, instance of Spatie\EventProjector\Models\StoredEvent given`. With this PR, the correct instance is passed.

fix: using StoredEvent model from config in Projectionist

---

src/HandleStoredEventJob.php
src/Projectionist.php
tests/ProjectionistTest.php
tests/TestClasses/Events/MoneyAdded.php

This PR adds support for Laravel Horizon [tags](https://laravel.com/docs/master/horizon#tags).
The docs state that we can add a tags function to any queueable entities and have them show up nicely in Horizon. Because Laravel Event Projector uses it's own `HandleStoredEventJob` which does not handle the user called event tags, currently the tags make little sense (see the screenshot below).
The first entry in this screenshot is an "auto" tag. The second entry is with custom tags set in the `ShouldBeStored` event and the third entry is how the tags looked like before the PR.

Add tags to events for Laravel Horizon support

---

tests/Console/ListCommandTest.php
tests/Console/RebuildCommandTest.php
tests/Console/ReplayCommandTest.php
tests/Console/ResetCommandTest.php

I replaced `$this->artisan()` with `Artisan::call()` in the failing tests. I could not really figure out why 5.7 would make the tests using `$this->artisan()` fail.
Anyhow, all tests are passing again, with backwards compatibility.

fix: tests are working again with L5.7

---

src/EventSubscriber.php
src/Projectionist.php
src/Projectors/ProjectsEvents.php

Another PR for correctly using StoredEvent and ProjectorStatus models defined in the config.
Also includes a tiny fix for #89: when using this package and hyn/multi-tenant, running tests out of the box should work fine now.

Referencing StoredEvent and ProjectorStatus from config, fix for #89

---

.gitignore
config/event-projector.php
src/Console/Concerns/ReplaysEvents.php
src/Console/ListCommand.php
src/Console/ReplayCommand.php
src/HandleStoredEventJob.php
src/Models/StoredEvent.php
src/Projectionist.php

1. Added supoort for Lumen framework
2. Added ```stored_event_job``` config option. You can redefine ```HandleStoredEventJob``` class.
3. Fixed bad usage of ```ProjectorStatus``` model. Removed any hardcode of table name, query builder, etc.
4. Added ```.idea``` to .gitignore

Lumen support & refactor

---

src/Models/StoredEvent.php
tests/EventSubscriberTest.php
tests/TestClasses/Events/MoneyAddedEventWithQueueOverride.php
tests/TestClasses/Projectors/BalanceProjector.php

Hopefully this seems like a good idea.  Allow defining queue name in events.  My specific use case is segregating low priority event processing into a separate queue, like imports, but this could also be handy to segregate event processing by domain.

allow overriding queue name

---

src/AggregateRoot.php
src/Projectors/ProjectsEvents.php
tests/AggregateRootTest.php
tests/TestCase.php
tests/TestClasses/AggregateRoots/AccountAggregateRootWithStoredEventSpecified.php
tests/TestClasses/Models/OtherStoredEvent.php

I have a multi-tenant application, so I need stored events for the main application, and stored events for each customer database. I need to be able to specify which stored event model to persist the aggregate's events to.
Also during this, I noticed `\Spatie\EventProjector\Projectors\ProjectsEvents@getStoredEventClass` is not used. I removed that method.

Specify stored event model for aggregates.

---

src/DiscoverEventHandlers.php

I follow the doc to disable auto discover projector & reactor feature (set `auto_discover_projectors_and_reactors` to an empty array), then execute `php artisan migrate:fresh` and get the error:
```
In Finder.php line 602:
You must call one of in() or append() methods before iterating over a Finde
r.
```
When `Symfony\Component\Finder`'s property `$dirs` is empty, `collect($files)` will throw an exception, so I think the easy solution is that don't execute the rest of code when there is no discovery path.

Disabling discovery break the artisan.

---

stubs/projector.stub
stubs/reactor.stub

Changes `Happended` (extra `d`) => `Happened` 
~If you wouldn't mind squashing these commits together, I made these edits on the GitHub website and committed them separately.~
Edit: Squashed the commits together. 😄

Fix inconsistent variable/method name in stub

---

src/Console/ListCommand.php

I was investigating why none of my events were actually taken into account, and noticed that the `event-project:list` command didn't actually output anything.
It seems like the intent of whoever wrote that command was to warn the user, stating that no reactor/projector was found, but the actual `$this->warn(...)` was forgotten.
This PR simply adds them, so that debugging is a little bit easier.

Actually warn when no projector/reactor is registered

---

CHANGELOG.md
config/event-projector.php
docs/advanced-usage/using-aliases-for-stored-event-classes.md
docs/installation-setup.md
src/Models/StoredEvent.php
tests/EventSubscriberTest.php
tests/Models/StoredEventTest.php

Add event_class_map for event class aliases

---

docs/using-reactors/writing-your-first-reactor.md

A reference to the old `rebuild` command got missed here in the docs.

Update rebuild command reference to replay

---

src/EventHandlers/HandlesEvents.php
tests/TestClasses/Projectors/ProjectorWithoutHandlesEvents.php

When you write a projector with a protected and or private method that uses an event, the projector will fail to handle an event thrown at it with the error: `call_user_func_array() expects parameter 1 to be a valid callback, cannot access protected method`.
It is fixed with my PR. This will only search for public methods in the projector and ignore internally used methods.

Only allow public projector methods to be auto detected

---

src/EloquentStoredEventRepository.php
tests/AggregateRootTest.php
tests/EventSerializers/EventSerializerTest.php
tests/TestCase.php
tests/TestClasses/AggregateRoots/AccountAggregateRoot.php
tests/TestClasses/AggregateRoots/StorableEvents/MoneyMultiplied.php

I have an app with a postgres database. Records don't return in order of insert for me so my apps tests were failing. This PR does two things:
* So that the aggregate has events applied in the correct order, the query will be ordered by id.
* Supports the `pgsql` driver for this test suite.

Ensure eloquent stored events are retrieved in order of ID.

---

UPGRADING.md
config/event-projector.php
docs/advanced-usage/storing-metadata.md
docs/advanced-usage/using-aliases-for-stored-event-classes.md
docs/advanced-usage/using-your-own-event-serializer.md
docs/advanced-usage/using-your-own-event-storage-model.md
docs/advanced-usage/using-your-own-event-storage-repository.md
src/AggregateRoot.php
src/EloquentStoredEventRepository.php
src/EventHandlers/EventHandler.php
src/EventHandlers/EventHandlerCollection.php
src/EventHandlers/HandlesEvents.php
src/Events/EventHandlerFailedHandlingEvent.php
src/Exceptions/InvalidEloquentStoredEventModel.php
src/Exceptions/InvalidStoredEvent.php
src/HandleStoredEventJob.php
src/Models/EloquentStoredEvent.php
src/Projectionist.php
src/StoredEvent.php
src/StoredEventRepository.php
tests/AggregateRootTest.php
tests/TestClasses/Models/InvalidEloquentStoredEvent.php
tests/TestClasses/Projectors/ProjectorThatWritesMetaData.php
tests/TestClasses/Repositories/OtherEloquentStoredEventRepository.php

- Makes it easier to upgrade
- Makes it easier if you just want to use a different model
- Will do nothing if you use a different repository
I've also moved the `StoredEvent` class out of the `models` folder to avoid confusion, as this is just a DTO and not an actual Laravel Model

Re-introduce the stored_event_model config

---

docs/advanced-usage/adding-and-removing-projectors-and-reactors.md
docs/advanced-usage/discovering-projectors-and-reactors.md
docs/advanced-usage/preparing-events.md
docs/advanced-usage/replaying-events.md
docs/advanced-usage/using-aliases-for-stored-event-classes.md
docs/getting-familiar-with-event-sourcing/introduction.md
docs/getting-familiar-with-event-sourcing/using-aggregates-to-make-decisions-based-on-the-past.md
docs/getting-familiar-with-event-sourcing/using-projectors-to-transform-events.md
docs/installation-setup.md
docs/introduction.md
docs/using-aggregates/creating-and-configuring-aggregates.md
docs/using-aggregates/writing-your-first-aggregate.md
docs/using-projectors/creating-and-configuring-projectors.md
docs/using-projectors/thinking-in-events.md
docs/using-projectors/writing-your-first-projector.md
docs/using-reactors/writing-your-first-reactor.md

A while ago, in #131, I said I'd add the docs for the function: `Projectionist::withoutEventHandler($class)`.
Here it is! I also included some typo fixes and link updates for the v3 docs.

Docs: Adding and Removing Projectors and Reactors

---

composer.json
src/Models/EloquentStoredEvent.php
tests/Models/StoredEventTest.php

In the version 3.x of `laravel-event-projector` the `laravel-schemaless-attributes` dependency was removed.
That dependency allowed us to use the following syntax to update an `EloquentStoredEvent`'s `meta_data` attribute:
~~~php
$event->meta_data['ip'] = '127.0.0.1';
~~~
This syntax is the one outlined in this package documentation.
With the dependency removal this syntax no longer works and an `ErrorException: Indirect modification of overloaded property` is thrown when trying to set a key in the `meta_data` property using the above notation.
This error is due that attributes from an Eloquent Model are retrieved due through the `__get` magic method and not accessed directly. This is a PHP limitation as it returns a copy of the value instead of a reference to the underlying array.
When …

[3.x] Revert to using laravel-schemaless-attributes for meta_data
